language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.6.1
  - 1.7.3
  - tip

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq memcached

install:
  - go get golang.org/x/tools/cmd/cover
  - go get -t -v -d

script:
  - go test -v -race -cover ./...
